### ISSUE TITLE
Failed to open stream (autoload_real.php)

### ISSUE THREAD

**Issue by josefarrugia** [pixelandtonic/CommerceEasyPost#1]
Hi there,

I am getting the following error prior to installing the plugin in CraftCMS:

`require(/Applications/MAMP/htdocs/website/craft/plugins/easypost/vendor/composer/../paragonie/random_compat/lib/random.php): failed to open stream: No such file or directory`

![image](https://user-images.githubusercontent.com/8568008/30063255-f4fef17c-9245-11e7-957f-ccefe9acd57c.png)

I have already copied the `easypost.php` config file to `craft/config`. 

What did I miss?

**Comment by lukeholder** [comment]
@josefarrugia I can't seem to reproduce. I can install and uninstall fine.

 Can you confirm you have made a full copy of the plugin folder into your plugin directory.

Can you also confirm your craft version, PHP version etc.

**Comment by josefarrugia** [comment]
Hey @lukeholder.

Yep, I can confirm I made a plugin folder in the plugin directory and copied the easypost.php file to the configuration direction. 

We're using the latest version of craft and PHP 7.1. Could it be a PHP issue?

**Comment by bymayo** [comment]
I'm also running in to this issue, copied the plugin to the plugin folder, clicked 'Plugins' in Craft settings and got the exact same error.

`require(/.../craft/plugins/easypost/vendor/composer/../paragonie/random_compat/lib/random.php): failed to open stream: No such file or directory`

PHP 7.0.20 and Craft CMS 2.6.2989

**Comment by lukeholder** [comment]
@bymayo @josefarrugia Just pushed a fix, re-download and try again. Thanks.
